### ISSUE TITLE
이전 계획

### ISSUE THREAD

**Issue by TaegyunKwon** [jdasam/pyScoreParser#6]
xml_matching의 *모든* 함수 , class에 대해 현재 상황과 이전 계획을 적어 놓을 수 있을까요?
유진이가 notion에 적은것도 참고해서 진행하면 더 편할거 같습니다.
https://www.notion.so/PyScoreParser-91093ed067714eba82ef1bea1d97066f

**Comment by luciaicull** [comment]
노션에 작성한 방식대로가 나을까요 아니면 지금처럼 코드 지우면 해당 부분에 주석처리 해두는 정도면 될까요?
